### ISSUE TITLE
How to fine-tune deepseek v2 models?

### ISSUE THREAD

**Issue by satheeshkatipomu** [deepseek-ai/DeepSeek-V2#40]
Hi,

Can you please give us instructions about fine-tuning deepseekv2 model? Can we `finetune.py` script from `DeepSeek-MoE`
https://github.com/deepseek-ai/DeepSeek-MoE/blob/main/finetune/finetune.py

**Comment by luofuli** [comment]
No plans...

**Comment by yiyepiaoling0715** [comment]
> No plans...

why,we have the needs

**Comment by TMelikhov** [comment]
We are also very interested to do this. So far our experiments have been unsuccessful. It would be incredible if we could get some clues.

**Comment by yiyepiaoling0715** [comment]
> We are also very interested to do this. So far our experiments have been unsuccessful. It would be incredible if we could get some clues.

what is the problem? i have use some repo like  MFTCoder/Firefly to train it successful except for the eval during training; and  loss decrease normal.   These training pipeline will be ok?

**Comment by yiyepiaoling0715** [comment]
> We are also very interested to do this. So far our experiments have been unsuccessful. It would be incredible if we could get some clues.
I have record the bugs during  match  deepseek-v2 to  training repos
can we have a wechat  to communicate these cases?  my :  yiyepiaoling0715

**Comment by yiyepiaoling0715** [comment]
> We are also very interested to do this. So far our experiments have been unsuccessful. It would be incredible if we could get some clues.


2024-07-26 16:03:47.197 | 07/26/2024 08:03:47-INFO-train_utils batch_shape=torch.Size([1, 4596]),batch_numel=4596 |  
-- | -- | --
  |   | 2024-07-26 16:03:47.197 | 07/26/2024 08:03:47-INFO-train_utils [TRAIN][train_task_index=0,task_loss=1.030632] |  
  |   | 2024-07-26 16:07:23.645 | 07/26/2024 08:07:23-INFO-train_utils eval_and_save_model in completed_steps= 45 |  
  |   | 2024-07-26 16:07:35.024 | Traceback (most recent call last): |  
  |   | 2024-07-26 16:07:35.024 | File "/lpai/code/mft-coder-zyy-dev/2c3fd4/mft_peft_hf/src/pefts/mft_accelerate.py", line 573, in <module> |  
  |   | 2024-07-26 16:07:35.025 | main() |  
  |   | 2024-07-26 16:07:35.025 | File "/lpai/code/mft-coder-zyy-dev/2c3fd4/mft_peft_hf/src/pefts/mft_accelerate.py", line 569, in main |  
  |   | 2024-07-26 16:07:35.026 | accelerate_train(accelerator, model, train_dataloader, valid_dataloader, optimizer, lr_scheduler, num_update_steps_per_epoch, len(train_dataset), args) |  
  |   | 2024-07-26 16:07:35.026 | File "/lpai-running/code/mft-coder-zyy-dev/2c3fd4/mft_peft_hf/src/pefts/train_utils.py", line 454, in accelerate_train |  
  |   | 2024-07-26 16:07:35.026 | stall_num_iter=eval_and_save_model(model=model,valid_dataloader=valid_dataloader, |  
  |   | 2024-07-26 16:07:35.026 | File "/lpai-running/code/mft-coder-zyy-dev/2c3fd4/mft_peft_hf/src/pefts/train_utils.py", line 178, in eval_and_save_model |  
  |   | 2024-07-26 16:07:35.026 | outputs = model( |  
  |   | 2024-07-26 16:07:35.026 | File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl |  
  |   | 2024-07-26 16:07:35.027 | return self._call_impl(*args, **kwargs) |  
  |   | 2024-07-26 16:07:35.027 | File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl |  
  |   | 2024-07-26 16:07:35.027 | return forward_call(*args, **kwargs) |  
  |   | 2024-07-26 16:07:35.027 | File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn |  
  |   | 2024-07-26 16:07:35.027 | ret_val = func(*args, **kwargs) |  
  |   | 2024-07-26 16:07:35.027 | File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1852, in forward |  
  |   | 2024-07-26 16:07:35.027 | loss = self.module(*inputs, **kwargs) |  
  |   | 2024-07-26 16:07:35.027 | File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl |  
  |   | 2024-07-26 16:07:35.027 | return self._call_impl(*args, **kwargs) |  
  |   | 2024-07-26 16:07:35.027 | File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1574, in _call_impl |  
  |   | 2024-07-26 16:07:35.027 | hook_result = hook(self, args, result) |  
  |   | 2024-07-26 16:07:35.027 | File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn |  
  |   | 2024-07-26 16:07:35.028 | ret_val = func(*args, **kwargs) |  
  |   | 2024-07-26 16:07:35.028 | File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 232, in _end_of_forward_hook |  
  |   | 2024-07-26 16:07:35.028 | self.get_param_coordinator(training=False).reset_step() |  
  |   | 2024-07-26 16:07:35.028 | File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 212, in reset_step |  
  |   | 2024-07-26 16:07:35.028 | assert_ints_same_as_other_ranks([m.id for m in self.__submodule_order]) |  
  |   | 2024-07-26 16:07:35.028 | File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn |  
  |   | 2024-07-26 16:07:35.028 | ret_val = func(*args, **kwargs) |  
  |   | 2024-07-26 16:07:35.028 | File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/utils.py", line 88, in assert_ints_same_as_other_ranks |  
  |   | 2024-07-26 16:07:35.028 | raise RuntimeError(f"disagreement between rank0 and rank{dist.get_rank()}: " |  
  |   | 2024-07-26 16:07:35.028 | RuntimeError: disagreement between rank0 and rank1: rank0: [4401208739789388772, 4331260760637291626, 4407682187513248870, 4425135281033919771, 4370670049129086120, 4289323405050526523, 4282140100162370942, 4258079813643025700, -4890141335760487581, 4287071622400720072, ...] rank1: [0, 1, 2, 4, 17, 5, 6, 7, 8, 9, 11, 10, 18, 12, 13, 16, 14, 15, 19, 355, 20, 21, 22, 23, 24, 26, 25, 356, 27, 349, 29, 30, 33, 31, 32, 34, 35, 38, 36, 37, 39, 40, 43, 41, 42, 44, 45, 48, 46, 47, 49, 50, 53, 51, 52, 54, 55, 58, 56, 57, 59, 60, 63, 61, 62, 64, 65, 68, 66, 67, 69, 70, 73, 71, 72, 74, 75, 78, 76, 77, 79, 80, 83, 81, 82, 84, 85, 88, 86, 87, 89, 90, 93, 91, 92, 94, 95, 98, 96, 97, 99, 100, 103, 101, 102, 104, 105, 108, 106, 107, 109, 110, 113, 111, 112, 114, 115, 118, 116, 117, 119, 120, 123, 121, 122, 124, 125, 128, 126, 127, 129, 130, 133, 131, 132, 134, 135, 138, 136, 137, 139, 140, 143, 141, 142, 144, 145, 148, 146, 147, 149, 150, 153, 151, 152, 154, 155, 158, 156, 157, 159, 160, 163, 161, 162, 164, 165, 168, 166, 167, 169, 170, 173, 171, 172, 174, 175, 178, 176, 177, 179, 180, 183, 181, 182, 184, 185, 188, 186, 187, 189, 190, 193, 191, 192, 194, 195, 198, 196, 197, 204, 205, 208, 206, 207, 209, 210, 213, 211, 212, 214, 215, 218, 216, 217, 219, 220, 223, 221, 222, 224, 225, 228, 226, 227, 229, 230, 233, 231, 232, 234, 235, 238, 236, 237, 239, 240, 243, 241, 242, 244, 245, 248, 246, 247, 249, 250, 253, 251, 252, 254, 255, 258, 256, 257, 259, 260, 263, 261, 262, 264, 265, 268, 266, 267, 269, 270, 273, 271, 272, 274, 275, 278, 276, 277, 279, 280, 283, 281, 282, 284, 285, 288, 286, 287, 289, 290, 293, 291, 292, 294, 295, 298, 296, 297, 299,
